### ISSUE TITLE
!sound bei whisper gibt nicht die verfügbaren sounds

### ISSUE THREAD

**Issue by DJKnaeckebrot** [marianwulf/Streamlabs-Chatbot-Scripts#7]
Wenn man den Bot anflüstert mit !sound bekommt man keine nachricht mit den verfügbaren sounds zurück gesendet

**Comment by marianwulf** [comment]
Leider liegt der Fehler nicht am Script, sondern Twitch unterbindet in manchen Fällen die Nachrichten um Missbrauch zu vermeiden. Als verifizierter Bot sollte dies besser funktionieren. Ich würde mich allerdings nicht drauf verlassen.

Siehe: https://github.com/tmijs/tmi.js/issues/333#issuecomment-712474914
